export const groupLabels: Record<string, string> = {
  Dashboard: "ড্যাশবোর্ড",
  Students: "শিক্ষার্থী",
  Courses: "কোর্স",
  Classes: "ক্লাস",
  Exams: "পরীক্ষা",
  Assignments: "অ্যাসাইনমেন্ট",
  "Books & Orders": "বই ও অর্ডার",
  Content: "কনটেন্ট",
};

export const permissionLabels: Record<string, string> = {
  can_view_dashboard: "ড্যাশবোর্ড দেখা",
  can_view_students: "শিক্ষার্থী দেখা",
  can_create_student: "শিক্ষার্থী যোগ করা",
  can_edit_student: "শিক্ষার্থী সম্পাদনা",
  can_delete_student: "শিক্ষার্থী মুছে ফেলা",
  can_view_course_enrollments: "কোর্স ভর্তির তথ্য দেখা",
  can_view_courses: "কোর্স দেখা",
  can_create_course: "কোর্স তৈরি করা",
  can_edit_course: "কোর্স সম্পাদনা",
  can_delete_course: "কোর্স মুছে ফেলা",
  can_publish_course: "কোর্স প্রকাশ করা",
  can_view_live_classes: "লাইভ ক্লাস দেখা",
  can_create_live_class: "লাইভ ক্লাস তৈরি করা",
  can_edit_live_class: "লাইভ ক্লাস সম্পাদনা",
  can_delete_live_class: "লাইভ ক্লাস মুছে ফেলা",
  can_view_recorded_classes: "রেকর্ডেড ক্লাস দেখা",
  can_manage_course_resources: "কোর্স রিসোর্স পরিচালনা",
  can_view_exams: "পরীক্ষা দেখা",
  can_create_exam: "পরীক্ষা তৈরি করা",
  can_edit_exam: "পরীক্ষা সম্পাদনা",
  can_delete_exam: "পরীক্ষা মুছে ফেলা",
  can_add_exam_questions: "পরীক্ষার প্রশ্ন যোগ করা",
  can_publish_exam: "পরীক্ষা প্রকাশ করা",
  can_publish_result: "ফলাফল প্রকাশ করা",
  can_view_results: "ফলাফল দেখা",
  can_view_leaderboard: "লিডারবোর্ড দেখা",
  can_manage_assignments: "অ্যাসাইনমেন্ট পরিচালনা",
  can_evaluate_assignments: "অ্যাসাইনমেন্ট মূল্যায়ন",
  can_view_books: "বই দেখা",
  can_create_book: "বই যোগ করা",
  can_edit_book: "বই সম্পাদনা",
  can_delete_book: "বই মুছে ফেলা",
  can_view_orders: "অর্ডার দেখা",
  can_update_order_status: "অর্ডার স্ট্যাটাস পরিবর্তন",
  can_manage_notices: "নোটিশ পরিচালনা",
  can_manage_teachers: "শিক্ষক পরিচালনা",
  can_manage_reviews: "রিভিউ পরিচালনা",
  can_manage_faq: "FAQ পরিচালনা",
  can_manage_home_content: "হোমপেজ কনটেন্ট পরিচালনা",
  can_manage_static_pages: "স্ট্যাটিক পেজ পরিচালনা",
};
